correlationAnalysis/correlationAnalysis/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('correlationVisualization/', include('correlationVisualization.urls')),
]

correlationAnalysis/correlationVisualization/urls.py
from django.urls import path
from . import views

app_name="CorrelationVisualization"

urlpatterns = [
    path('', views.get, name='get',),
    path('corr/', views.post, name='post'),
    path('corr/legend', views.legend, name='legend')
]

correlationAnalysis/correlationVisualization/models.py
from django.db import models

# Create your models here.

correlationAnalysis/correlationVisualization/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import TemplateView
from . import SingleDomain_DataType_DataUsage_Relative_hover as hover

    
def get(request, **kwargs):
    return render(request, 'index.html', context=None)

def post(request):
    domain = request.POST['domain']
    amount = int(request.POST['corr'])
    corr = hover.plotHeatmap(domain, amount)
    corr = corr.to_dict()
    context_dict = {}
    context_dict['res'] = corr
    context_dict['domain'] = hover.getDomainName()
    context_dict['sampleSize'] = hover.getSampleSize()
    print(hover.getDomainName())
    return render(request, 'resultHover.html', context=context_dict)

def legend(request):
    return render(request, 'legend.html', context=None)

correlationAnalysis/correlationVisualization/templates/index.html
{% load tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% tailwind_css %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Correlation Visualization</title>
</head>
<body class="h-100 text-center text-black bg-slate-100">
    <h1 class="text-4xl m-4 items-center">Correlation-Analysis Visualization</h1>
    <form method="POST" action="corr/" class="bg-white rounded-md py-10 px-12 shadow-lg">
        {% csrf_token %}
        <p class="m-4" align="left" style="font-size:14pt;">In 2019 Gregory, Groth, Scharnhorst and Wyatt conducted a 
            <a href="https://arxiv.org/abs/1909.00464" style="color: rgb(59, 130, 246)">survey</a>, 
            resulting in the largest known dataset on how researchers 
            and support professionals discover and use data. A total of 1677 respondents out of 105 countries make up 
            this dataset, working in a wide variety of disciplinary domains. This web application shows the relationship 
            between the disciplinary domains of the respondents and the data types they usually need and how they use those data.
            </br></br>
            The relationship will be shown with the help of a heatmap. 
            A heatmap is a data visualization technique, where in this case the correlation between the variables 
            is shown in a two dimensional grid, where a more saturated cell represents a higher correlation.
            </br></br>
            The participants had the freedom to choose more than one domain they work in, together with multiple data needs and uses. 
            In this analysis only participants choosing only one disciplinary domain have been considered, excluding the 4 grouped domains 
            at the end of the list. Here participants only choosing the two named domains have been considered.
            </br>
            These grouped domains have been selected by choosing the top four frequent itemsets using the  <a href="https://en.wikipedia.org/wiki/Apriori_algorithm" style="color: rgb(59, 130, 246)">apriori algorithm</a>.
            </br></br>
            The chosen data types and needs have been weighted for each user, where each choice had a weight of one divided by the total 
            number of data types and uses each participant chose.
        </p>
    </br>
        <h1 class="text-center text-xl">Select a disciplinary domain:</h1>
            <svg class="w-2 h-2 absolute top-0 right-0 m-4 pointer-events-none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 412 232"><path d="M206 171.144L42.678 7.822c-9.763-9.763-25.592-9.763-35.355 0-9.763 9.764-9.763 25.592 0 35.355l181 181c4.88 4.882 11.279 7.323 17.677 7.323s12.796-2.441 17.678-7.322l181-181c9.763-9.764 9.763-25.592 0-35.355-9.763-9.763-25.592-9.763-35.355 0L206 171.144z" fill="#648299" fill-rule="nonzero"/></svg>
          <select class="border border-gray-300 rounded-full text-gray-600 h-10 pl-5 pr-10 bg-white hover:border-gray-400 focus:outline-none appearance-none" id="domain" name="domain">
            <option value="disc_agricul">Agriculture</option>
            <option value="disc_artshuman">Arts and Humanities</option>
            <option value="disc_astronom">Astronomy</option>
            <option value="disc_biochem">Biochemistry, Genetics</option>
            <option value="disc_biological">Biology</option>
            <option value="disc_busin">Business</option>
            <option value="disc_chemeng">Chemical Engineering</option>
            <option value="disc_chem">Chemistry</option>
            <option value="disc_compsci">Computer Science, IT</option>
            <option value="disc_decisionsci">Decision Sciences</option>
            <option value="disc_dentist">Dentistry</option>
            <option value="disc_earthplanet">Earth and Planetary Sciences</option>
            <option value="disc_econ">Economics, Finance</option>
            <option value="disc_energy">Energy</option>
            <option value="disc_engtech">Engineering and Technology</option>
            <option value="disc_environ">Environmental Sciences</option>
            <option value="disc_healthprof">Health Professions</option>
            <option value="disc_immun">Immunology, Microbiology</option>
            <option value="disc_matlsci">Materials Science</option>
            <option value="disc_math">Mathematics</option>
            <option value="disc_med">Medicine</option>
            <option value="disc_multi">Multidsciplinary</option>
            <option value="disc_neuro">Neuroscience</option>
            <option value="disc_socsci">Social Sciences</option>
            <option value="disc_pharma">Pharmalogy and Toxicology</option>
            <option value="disc_nurs">Nursing</option>
            <option value="disc_physics">Physics</option>
            <option value="disc_psych">Psychology</option>
            <option value="disc_vet">Veterinary</option>
            <option value="disc_infosci">Information Sciences</option>
            <option value="disc_other">Other</option>
            <option value="compsci_engtech">Computer Science, IT - Engineering Technologies</option>
            <option value="biochem_bio">Biochemistry - Biological Sciences</option>
            <option value="environ_bio">Environmental Sciences - Biological Sciences</option>
            <option value="med_health">Medicine - Health Professions</option>
        </select>
        
        </br>
        </br>
    </br>
        <p class="m-4" align="left" style="font-size:14pt;">Together with the heatmap, a table with the top correlations will be shown. Please select how many rows you want to see below.</p>
    </br>
        <h1 class="text-center text-xl">Select number of rows:</h1>
        <svg class="w-2 h-2 absolute top-0 right-0 m-4 pointer-events-none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 412 232"><path d="M206 171.144L42.678 7.822c-9.763-9.763-25.592-9.763-35.355 0-9.763 9.764-9.763 25.592 0 35.355l181 181c4.88 4.882 11.279 7.323 17.677 7.323s12.796-2.441 17.678-7.322l181-181c9.763-9.764 9.763-25.592 0-35.355-9.763-9.763-25.592-9.763-35.355 0L206 171.144z" fill="#648299" fill-rule="nonzero"/></svg>
        <select class="border border-gray-300 rounded-full text-gray-600 h-10 pl-5 pr-10 bg-white hover:border-gray-400 focus:outline-none appearance-none" id="corr" name="corr">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
                <option value="6">6</option>
                <option value="7">7</option>
                <option value="8">8</option>
                <option value="9">9</option>
                <option value="10">10</option>
        </select>
        <button type="submit" value="submit" class="bg-blue-500 hover:bg-blue-600 focus:outline-none rounded-md px-6 py-3 mx-auto block text-white transition duration-500 ease-in-out mt-8">Create Heatmap</button>
      </form>
</body>
</html>

correlationAnalysis/correlationVisualization/templates/resultHover.html
{% load static %}
{% load tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% tailwind_css %}
    <meta charset="UTF-8" />
    <script src="https://cdn.tailwindcss.com"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
    />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
    <title>Correlation Analysis</title>

    <link
    href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp"
    rel="stylesheet"
    />
  </head>
  <body class="h-100 text-center text-black bg-white">
    <h1 class="text-4xl m-4 items-center">Correlation Analysis Result</h1>
    <h2 class="text-2xl m-2 items-center">{{ domain }}</h1>
    <h2 class="text-2xl m-2 items-center">Sample Size: {{ sampleSize }}</h1>

<!-- Code modified -->
<!-- https://www.d3-graph-gallery.com/graph/heatmap_tooltip.html -->
<!-- Load d3.js -->
<script src="https://d3js.org/d3.v4.js"></script>
<a href="{% url 'CorrelationVisualization:legend' %}" style="color: rgb(59, 130, 246)">Legend</a> for heatmap variables
<!-- Create a div where the graph will take place -->
<div id="heatmap" class="flex items-center justify-center bg-white rounded-md py-10 px-12 shadow-lg"></div>
<script>

// set the dimensions and margins of the graph
var margin = {top: 10, right: 10, bottom: 200, left: 200},
  width = 800 - margin.left - margin.right,
  height = 750 - margin.top - margin.bottom;

// append the svg object to the body of the page
var svg = d3.select("#heatmap")
.append("svg")
  .attr("width", width + margin.left + margin.right)
  .attr("height", height + margin.top + margin.bottom)
.append("g")
  .attr("transform",
        "translate(" + margin.left + "," + margin.top + ")");

// Labels of row and columns
var myGroups = ["Observational/Empirical (Type)", "Experimental (Type)", "Simulation (Type)", "Derived/Compiled (Type)", "Other Types", "Basis for new study", "Calibration", "Benchmarking", "Verification", "Input", "Generating new ideas", "Teaching", "Prepare new project/proposal", "Experimental Use", "Identifying trends/predictions", "Comparison", "Summarizations", "Integrate with other data", "Other Uses"]

// Build X scales and axis:
var x = d3.scaleBand()
  .range([ 0, width ])
  .domain(myGroups)
  .padding(0.01);
svg.append("g")
  .attr("transform", "translate(0," + height + ")")
  .call(d3.axisBottom(x))
  .selectAll("text")  
  .style("text-anchor", "end")
  .style("font-size", 14)
  .attr("dx", "-.8em")
  .attr("dy", ".15em")
  .attr("transform", "rotate(-65)");
  

// Build Y scales and axis:
var y = d3.scaleBand()
  .range([ height, 0 ])
  .domain(myGroups)
  .padding(0.01);
svg.append("g")
  .style("font-size", 14)
  .call(d3.axisLeft(y));

// Build color scale
var myColor = d3.scaleLinear()
  .range(["white", "#3b82f6"])
  .domain([0,1])

//Read the data
d3.csv("{% static '/correlationVisualization/files/correlations.csv' %}", function(data) {

  // create a tooltip
  var tooltip = d3.select("#heatmap")
    .append("div")
    .style("opacity", 0)
    .attr("class", "tooltip")
    .style("background-color", "white")
    .style("border", "solid")
    .style("border-width", "2px")
    .style("border-radius", "2px")
    .style("padding", "5px")

  // Three function that change the tooltip when user hover / move / leave a cell
  var mouseover = function(d) {
    tooltip.style("opacity", 1)
  }
  var mousemove = function(d) {
    tooltip
      .html(d.Group1 + " - " + d.Group2 + ": " + d.Value)
      .style("left", (d3.mouse(this)[0]+350) + "px")
      .style("top", (d3.mouse(this)[1]+150) + "px")
  }
  var mouseleave = function(d) {
    tooltip.style("opacity", 0)
  }

  // add the squares
  svg.selectAll()
    .data(data, function(d) {return d.Group1+':'+d.Group2;})
    .enter()
    .append("rect")
      .attr("x", function(d) { return x(d.Group1) })
      .attr("y", function(d) { return y(d.Group2) })
      .attr("width", x.bandwidth() )
      .attr("height", y.bandwidth() )
      .style("fill", function(d) { return myColor(d.Value)} )
    .on("mouseover", mouseover)
    .on("mousemove", mousemove)
    .on("mouseleave", mouseleave)
})

</script>

    <div class="flex items-center justify-center mt-8 bg-white rounded-md py-10 px-12 shadow-lg">
        <div class="col-span-12">
          <h2 class="text-2xl m-2 items-center">Top correlations</h2>

          <table class="table text-gray-400 space-y-6 text-sm m-12">
            <thead class="bg-blue-500 text-white mb-12">
              <tr>
                <th class="p-3">Corr Value</th>
                <th class="p-3">Interpretation</th>
              </tr>
            </thead>
            <tbody>
              <tr class="bg-blue-200 lg:text-black">
                <td class="p-3 font-medium capitalize">0 - 0.29</td>
                <td class="p-3 font-medium capitalize">No correlation</td>
              </tr>
              <tr class="bg-blue-200 lg:text-black">
                <td class="p-3 font-medium capitalize">0.3 - 0.49</td>
                <td class="p-3 font-medium capitalize">Weak correlation</td>
              </tr>
              <tr class="bg-blue-200 lg:text-black">
                <td class="p-3 font-medium capitalize">0.5 - 0.69</td>
                <td class="p-3 font-medium capitalize">Moderate correlation</td>
              </tr>
              <tr class="bg-blue-200 lg:text-black">
                <td class="p-3 font-medium capitalize">0.7 - 0.89</td>
                <td class="p-3 font-medium capitalize">High correlation</td>
              </tr>
              <tr class="bg-blue-200 lg:text-black">
                <td class="p-3 font-medium capitalize">0.9 - 1</td>
                <td class="p-3 font-medium capitalize">Very high correlation</td>
              </tr>
            </tbody>
          </table>
            <table class="table text-gray-400 space-y-6 text-sm m-12">
              <thead class="bg-blue-500 text-white mb-12">
                <tr>
                  <th class="p-3">Variables</th>
                  <th class="p-3">Value</th>
                </tr>
              </thead>
              <tbody>
                {% for keys, value in res.items %}
                <tr class="bg-blue-200 lg:text-black">
                    <td class="p-3 font-medium capitalize">
                    {% for key in keys %}
                        {{ key }} </br>
                    {% endfor %}
                    </td>
                    <td class="p-3">{{ value }}</td>
                </tr>
                {% endfor %}
               </tbody>
            </table>
          </div>
        </div>
    

  </body>
</html>

correlationAnalysis/theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>